### ISSUE TITLE
How to setup SSH key on local GIT

### ISSUE THREAD

**Issue by BarryGallagher** [code-co-op/learning-web-development#24]
Rather than having to pass a username/password with each push, how can I setup a SSH locally.

The solution should be documented as a Wiki.

**Comment by awflwafl** [comment]
@BarryGallagher Does this article from GitHub help?
https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by BarryGallagher** [comment]
Yes, I went through the process last night. Planning on documenting in a Wiki.

**Comment by BarryGallagher** [comment]
This issue can now be close as the steps are documented at https://github.com/code-co-op/learning-web-development/wiki/Add-SSH-key-to-Github-account-for-a-Windows-user

**Comment by BarryGallagher** [comment]
This issue can now be close as the steps are documented at https://github.com/code-co-op/learning-web-development/wiki/Add-SSH-key-to-Github-account-for-a-Windows-user
